accounts/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('loginpage/', views.loginPage, name="loginpage"),
    path('loginpage1/', views.loginpage1, name="loginpage1"),
    path('registerpage/', views.registerPage, name="registerpage"),
    path('logout/', views.logoutUser, name="logout"),
   # path('', views.home, name='home'),
    path('activate/<slug:uidb64>/<slug:token>',
         views.activate, name='activate'),
    #path('accounts/', views.signup_redirect, name='signup_redirect'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),

]

knu_tech_prac/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import ResetPasswordView
urlpatterns = [
    path("", include("syt_app.urls")),
    path("statistics/", include("stats.urls")),
    path("user/", include("stats.userUrls")),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path("accounts/", include("allauth.urls")),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('accounts/', include('social_django.urls', namespace="social")),

]

stats/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.StatsView.as_view(), name="statistics"),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import User


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

accounts/views.py
from django.dispatch import receiver
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.http import HttpResponse, HttpResponseRedirect
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CreateUserForm as SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .token import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from allauth.account.utils import perform_login
from allauth.exceptions import ImmediateHttpResponse
from allauth.socialaccount.signals import pre_social_login
from django.conf import settings


@receiver(pre_social_login)
def link_to_local_user(sender, request, sociallogin, **kwargs):
    email_address = sociallogin.account.extra_data['email']
    users = User.objects.filter(email=email_address)
    if users:
        user = users[0]
        if user.is_active:
            perform_login(request, user, email_verification=False)
            raise ImmediateHttpResponse(
                redirect(settings.LOGIN_REDIRECT_URL.format(id=request.user.id)))
        else:
            raise ImmediateHttpResponse(redirect('loginpage'))


# Create your views here.


def loginPage(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            form = login(request, user)
            messages.success(request, f' wecome {username} !!')
            return redirect('create_paste')
        else:
            messages.info(request, f'account done not exit plz sign in')
    form = CreateUserForm()
    return render(request, 'accounts/loginpage.html', {'form': form, 'title': 'log in'})

def loginpage1(request):
    return redirect('accounts:loginpage')
def registerPage(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            # save form in the memory not in database
            to_email = form.cleaned_data.get('email')
            users = User.objects.filter(email=to_email)
            if users:
                user = users[0]
                if user.is_active:

                    return render(request, 'accounts/already_exist.html')
                elif user.is_active == 0:

                    return render(request, 'accounts/already_exist.html')
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            # to get the domain of the current site
            current_site = get_current_site(request)
            mail_subject = 'Activation link of your account'
            message = render_to_string('accounts/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })

            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()

            return render(request,'accounts/please_confirm.html')
    else:
        form = SignupForm()
    return render(request, 'accounts/registerpage.html', {'form': form})


@login_required
def logoutUser(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("create_paste")


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, 'accounts/confirmed_user.html')

    else:
        return HttpResponse('Activation link is invalid!')


def signup_redirect(request):
    messages.error(request, "Something wrong here, it may be that you already have account!")
    return redirect("home.html")


def password_reset_complete(request):
    return redirect("password_reset_complete.html")


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'password/password_reset.html'
    email_template_name = 'password/password_reset_email.html'
    subject_template_name = 'password/password_reset_subject.html'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('accounts:loginpage')

accounts/templates/password/password_reset.html
{% load static %}
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Login</title>
    <style>
        body {
            background: radial-gradient(56.06% 56.06% at 50% 50%, rgba(226, 238, 243, 0) 0%, #C1D4DE 100%);
            mix-blend-mode: normal;
            background-attachment: fixed;
            font-family: JuraBold;
        }
    </style>

</head>
<body >
    <div class="form-content my-3 p-3 mt-10 mb-1"style="top:30%; ">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card  border-0 rounded-lg mt-5 mb-10" style="border-radius: 1rem;background: linear-gradient(236.18deg, #16304B 16.12%, rgba(22, 48, 75, 0.58) 93.17%);
box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.5);
border-radius: 5px;">
                        <div class=" justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center mt-5 mb-10"style="color: white">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div  role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">

                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                                       <div class=" text-center">
                            <div >

                            <p class="text-center mt-5 mb-0" style="color: white">Don"t have an account? <a
                                    href="{% url 'accounts:registerpage' %}" class="fw-bold text-body"><i
                                    style="color: cornflowerblue">Sign
                                up.</i></a></p>
                                <a href="{% url 'accounts:loginpage' %}">Back To Login</a><br>
                            </div>
                        </div>



                                <div class="form-row">




                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-5">
                                        <button type="submit" class="col-md-12 btn btn-dark" style="position:absolute;top:110%;background: rgba(0, 15, 46, 0.8);
border-radius: 5px;width:400px;height:60px; font-size: 30px;">
                                            Reset Password
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>

                </div>
            </div>
        </div>

  </div>
</body>
{% endblock content %}

accounts/templates/password/password_reset_complete.html
{% load static %}
<link rel="stylesheet" href="{% static 'main.css' %}">
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info" style="font-family: JuraBold;">
                        Your password has been set. You may go ahead and <a href="{% url 'accounts:loginpage' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/password/password_reset_confirm.html
{% load static %}
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Login</title>
    <style>
        body {
            background: radial-gradient(56.06% 56.06% at 50% 50%, rgba(226, 238, 243, 0) 0%, #C1D4DE 100%);
            mix-blend-mode: normal;
            background-attachment: fixed;
            font-family: JuraBold;
        }
    </style>

</head>
<body>
    <div class="form-content my-3 p-3">
        <div class="container py-5 "style="margin-top: 10%">
            <div class="row justify-content-center">
                <div class="col-lg-5" >
                    {% if validlink %}
                        <div class="card shadow-2-strong mt-0 mb-3"style="border-radius: 1rem;background: linear-gradient(236.18deg, #16304B 16.12%, rgba(22, 48, 75, 0.58) 93.17%);
box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.5);
border-radius: 5px;">
                            <div class=" justify-content-center">
                              <h3 class="font-weight-light my-4 text-center"style="color: white">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST" action="{% url 'accounts:loginpage1' %}">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">

                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter new password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">

                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm new password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-5 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset" style="background: rgba(0, 15, 46, 0.8);
border-radius: 5px; position: absolute;top:100%;height: 120%">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </body>
{% endblock content %}

accounts/templates/password/password_reset_done.html
{% block content %}
<link rel="stylesheet" href="{% static 'main.css' %}">
	<!--Password reset sent-->
<div class="container p-5" style="font-family: JuraBold; ">
  	<h2 class="font-weight-bold mt-3">Password reset sent</h2>
		<hr>
		<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
  </div>

{% endblock %}

accounts/templates/password/password_reset_email.html
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/password/password_reset_subject.html
Password reset email