accounts/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('loginpage/', views.loginPage, name="loginpage"),
    path('loginpage1/', views.loginpage1, name="loginpage1"),
    path('registerpage/', views.registerPage, name="registerpage"),
    path('logout/', views.logoutUser, name="logout"),
   # path('', views.home, name='home'),
    path('activate/<slug:uidb64>/<slug:token>',
         views.activate, name='activate'),
    #path('accounts/', views.signup_redirect, name='signup_redirect'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),

]

knu_tech_prac/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import ResetPasswordView
urlpatterns = [
    path("", include("syt_app.urls")),
    path("statistics/", include("stats.urls")),
    path("user/", include("stats.userUrls")),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path("accounts/", include("allauth.urls")),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('accounts/', include('social_django.urls', namespace="social")),

]

stats/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.StatsView.as_view(), name="statistics"),
]

syt_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.PasteCreateView.as_view(), name="create_paste"),
    path("<slug:short_url>", views.DisplayPasteView.as_view(), name='display_user_paste'),
    path("edit/<slug:short_url>", views.EditPasteView.as_view(), name='edit_user_paste'),
    path("clipaste/<slug:short_url>", views.console_paste_creation, name="console_get_paste"),
    path("clipaste/", views.console_paste_creation, name="console_create_paste"),
    path("delete/<int:id>", views.DeletePasteView.as_view(), name='delete_paste')
]

syt_app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Paste(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=300)
    pub_date = models.DateTimeField(default=datetime.now)
    expires = models.DateTimeField(null=True, blank=True)
    text = models.TextField()

    LANGUAFE_CHOICES = [
        ("text/x-python", "Python"),
        ("text/x-csharp", "C#"),
        ("text/x-c++src", "C++"),
        ("text/x-go", "Go"),
        ("text/javascript", "JavaScript"),
        ("text/x-java", "Java"),
        ("text/x-php", "PHP"),
        ("text/x-csrc", "C")
    ]
    language = models.CharField(max_length=20, choices=LANGUAFE_CHOICES)
    CATEGORY_CHOICES = [
        ("Algorithms", "Algorithms"),
        ("Web-development", "Web-development"),
        ("Scripts", "Scripts"),
        ("Poetry", "Poetry"),
        ("Programming", "Programming"),
        ("Other", "Other")
    ]
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default="Other")
    is_private = models.BooleanField(default=False)
    short_url = models.CharField(max_length=8, default="", unique=True)

    objects = models.Manager()

    def __str__(self):
        return f"{self.title}:{self.author}:{self.is_private}"

syt_app/forms.py
from django import forms
from syt_app.models import Paste
from syt_app.utils import transform_expired_choice


class PasteForm(forms.ModelForm):
    CHOICES = [(transform_expired_choice(1), "1 hour"),
               (transform_expired_choice(6), "6 hours"),
               (transform_expired_choice(12), '12 hours'),
               (transform_expired_choice(24), '1 day'),
               (None, 'Never')]
    expires = forms.DateTimeField(input_formats=["%d/%m/%y %H:%M:%S"], widget=forms.Select(choices=CHOICES),
                                  required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.initial:
            prev_choices = self.fields['expires'].widget.choices
            prev_choices.insert(0, (self.instance.expires, "Don't change"))
            self.fields['expires'] = forms.DateTimeField(input_formats=["%d/%m/%y %H:%M:%S"],
                                                         widget=forms.Select(choices=prev_choices))


class AuthorizedCreatePasteForm(PasteForm):
    as_guest = forms.BooleanField(required=False)

    class Meta:
        model = Paste
        fields = ["title", "language", "expires", "text", "as_guest", "category", "is_private"]


class AnonymousCreatePasteForm(PasteForm):
    class Meta:
        model = Paste
        fields = ["title", "language", "expires", "text", "category"]

syt_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden, HttpResponse
from django.views.generic import View
from syt_app.forms import AnonymousCreatePasteForm, AuthorizedCreatePasteForm
from syt_app.utils import generate_short_url, generate_side_panel_content
from syt_app.models import Paste
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
from django.utils.timezone import make_aware


@csrf_exempt
def console_paste_creation(request, *args, **kwargs):
    if request.method == 'POST':
        short_url = generate_short_url(8)
        text = request.POST.get('text', False)
        if text:
            new_paste = Paste(author=None,
                              title=request.POST.get('title', "console_created_paste"),
                              language=request.POST.get('language', "text/x-python"),
                              text=request.POST.get('text'),
                              category="Other",
                              short_url=short_url,
                              is_private=False)
            new_paste.save()
            return HttpResponse(f"{short_url}")
        return HttpResponse("text field should be filled")
    elif request.method == 'GET':
        short_url = kwargs.get('short_url', False)
        if short_url:
            return HttpResponse(f"{Paste.objects.get(short_url=kwargs['short_url']).text}")
        return HttpResponse("help text")


class PasteCreateView(View):
    template_name = "create_paste.html"

    def get(self, request, *args, **kwargs):
        random_paste, random_paste_expires = generate_side_panel_content(1)
        if request.user.is_authenticated:
            form = AuthorizedCreatePasteForm()
            return render(request, self.template_name, context={"form": form,
                                                                "random_paste": random_paste,
                                                                "random_paste_expires": random_paste_expires})

        form = AnonymousCreatePasteForm()
        return render(request, self.template_name, context={"form": form,
                                                            "random_paste": random_paste,
                                                            "random_paste_expires": random_paste_expires})

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            form = AuthorizedCreatePasteForm(request.POST)
        else:
            form = AnonymousCreatePasteForm(request.POST)

        short_url = generate_short_url(8)

        if form.is_valid():
            user_id = request.user.id
            if user_id is not None and not form.cleaned_data['as_guest']:
                user = User.objects.get(id=user_id)
            else:
                user = None  # Anonymous user

            new_paste = Paste(author=user,
                              title=form.cleaned_data['title'],
                              language=form.cleaned_data['language'],
                              expires=form.cleaned_data['expires'],
                              text=form.cleaned_data['text'],
                              category=form.cleaned_data['category'],
                              short_url=short_url,
                              is_private=form.cleaned_data.get('is_private', False))

            new_paste.save()
            return redirect('display_user_paste', short_url=f"{short_url}")
        return HttpResponseForbidden()


class DisplayPasteView(View):
    template_name = 'display_paste.html'

    def get(self, request, short_url=None, *args, **kwargs):
        if short_url is not None:
            paste = Paste.objects.get(short_url=short_url)
            user = request.user
            if ((paste.is_private and user.id == paste.author.id) or not paste.is_private) and (paste.expires is None or paste.expires > make_aware(datetime.now())):
                random_paste, random_paste_expires = generate_side_panel_content(1)
                #random_paste, random_paste_expires = 1, 1
                return render(request, self.template_name, context={"paste": paste,
                                                                    "random_paste": random_paste,
                                                                    "random_paste_expires": random_paste_expires})
            return HttpResponseForbidden()


class EditPasteView(View):
    template_name = 'edit_paste.html'

    def get(self, request, short_url=None, *args, **kwargs):
        paste = Paste.objects.get(short_url=short_url)
        user = request.user
        if user is not None and paste.author is not None:
            if user.id == paste.author.id and user.id is not None and (paste.expires is None or paste.expires > make_aware(datetime.now())):
                random_paste, random_paste_expires = generate_side_panel_content(1)
                form = AuthorizedCreatePasteForm(instance=paste)
                return render(request, self.template_name, context={"form": form,
                                                                    "random_paste": random_paste,
                                                                    "random_paste_expires": random_paste_expires,
                                                                    'short_url': paste.short_url})
        return HttpResponseForbidden()

    def post(self, request, short_url=None, *args, **kwargs):
        user_id = request.user.id
        form = AuthorizedCreatePasteForm(request.POST)
        if form.is_valid() and user_id == Paste.objects.get(short_url=short_url).author.id:
            Paste.objects.filter(short_url=short_url).update(title=form.cleaned_data['title'],
                                                             language=form.cleaned_data['language'],
                                                             expires=form.cleaned_data['expires'],
                                                             category=form.cleaned_data['category'],
                                                             text=form.cleaned_data['text'],
                                                             is_private=form.cleaned_data.get('is_private', False))
            return redirect('display_user_paste', short_url=f"{short_url}")
        return HttpResponseForbidden()


class DeletePasteView(View):

    def delete(self, request, id, *args, **kwargs):
        user_id = request.user.id
        paste = Paste.objects.get(id=id)
        if not request.user.is_anonymous and user_id == paste.author.id:
            paste.delete()
            return redirect('user_view')
        return HttpResponseForbidden()

syt_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SYT</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.47.0/codemirror.min.css">
    <link rel="stylesheet" href="{% static 'landcss/light.css'%}">
    <link rel="stylesheet" href="{% static 'landcss/dark.css'%}">


    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.47.0/codemirror.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.47.0/mode/javascript/javascript.min.js"></script>
    <script src="{% static 'js/clike.js'%}"></script>
    <script src="{% static 'js/python.js'%}"></script>
    <script src="{% static 'js/go.js'%}"></script>
    <script src="{% static 'js/php.js'%}"></script>
    <script src="{% static 'js/html.js'%}"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="{% static 'create_paste.css' %}">

    <style>
    .text_area {
        background-color: white;
        height: 664px;
    }
    </style>
    {% block styleBlock %}
    {% endblock %}
</head>
<body class="main_bg" style="display: block">

{% block tabBar %}
 <!-- верхнє меню -->
    <ul class="transparent_bg " id="mynav" style="z-index: 1000; justify-content: center; padding-left: 50px; padding-right: 61px;  " >

        {% block sign_in %}
        {% if request.user.is_authenticated %}
        <li style="height: 111px; width: 15%; margin-right: 70px;" >
            <div class="up_pan_buttons up_button_text" >
                <a href="{% url 'user_view' %}" class="up_pan_buttons_text">My profile</a>
            </div>
        </li>
        {% else %}
        <li style="height: 111px; width: 15%; margin-right: 70px;" >
            <div class="up_pan_buttons up_button_text" >
                <a href="{% url 'accounts:registerpage' %}" class="up_pan_buttons_text">Sign in</a>
            </div>
        </li>
        {% endif %}
        {% endblock %}
        {% block log_in %}
        {% if request.user.is_authenticated %}
        <li style=" width: 15%;">
            <div class="up_pan_buttons up_button_text">
                <a href="{% url 'accounts:logout' %}" class="up_pan_buttons_text">Log out</a>
            </div>
        </li>
        {% else %}
        <li style=" width: 15%;">
            <div class="up_pan_buttons up_button_text">
                <a href="{% url 'accounts:loginpage' %}" class="up_pan_buttons_text">Log in</a>
            </div>
        </li>
        {% endif %}
        {% endblock %}
        {% block create_paste %}
        <li style=" width: 20%;"><a class="font40_bold up_pan_menu_label" href="{% url 'create_paste' %}">New Paste</a></li>
        {% endblock %}
        {% block public_pastes %}
        <li style=" width: 20%;"><a class="font40_bold up_pan_menu_label" href="#news">Public pastes</a></li>
        {% endblock %}
        {% block statistics %}
        <li style=" width: 20%;"><a class="font40_bold up_pan_menu_label" href="{% url 'statistics' %}">Statistics</a></li>
        {% endblock %}
        <li style=" width: 5%;">
            <img src="{%static 'images/SYT_logo.png'%}" style="height: 93px; width: 66px; margin-top: 10px;"/>
        </li>
    </ul>
{% endblock %}

{% block mainPart %}
    <!--основна частина -->
    <div class="main_grid" onLoad="await new Promise(resolve => setTimeout(resolve, 1000))">
        <!--біле поле для нового пейсту-->
        <div id="main_post" class="text_area"   >

            <!--шапка поля -->
            <div id ="mainTitle" class="over_grid over_title" style="background-color: #000F2E; ">
                New paste
            </div>
              {% block mainPartContent %}
            <!--текст нового пейсту-->
            <div style="margin: 0px 50px 0px 50px">
               <textarea id="codeeditor" rows="40" cols="100" class="child_text_area" ></textarea>
            </div>
            {% endblock %}
        </div>
        <!--поле для рандомного пейсту -->
        <div class="sige_paste"  style=" border: #000F2E 1px; height: 664px; display: block; font-family: 'JuraBold' ">
            <!--шапка поля -->
            <div  class="over_grid_random over_title_random "  style="background-color: #000F2E; ">
                Random paste
            </div>
            <!--заголовок для пейсту-->
            <div  style=" height: 39px;  border-bottom: 1px solid #788897;">
                <!--назва пейсту-->
                <div  style="float: left; font-size: 22px; margin-left: 29px; color: #FFFFFF;" >
                    <a href="{{random_paste.short_url}}" class="header_random_title">{{ random_paste.title }}</a>
                </div>
                <!--автор пейсту-->
                 <div style="float: right; font-size: 16px; margin-right: 29px; color: #81C7EB;">
                     {% if random_paste.author  %}
                     {{ random_paste.author }}
                     {% else %}
                     Guest
                     {% endif %}
                </div>

            </div>
            <!--текст пейсту -->
            <div id="randomCode" style="margin-top: 25px;">

            </div>

        </div>
        {% block settingsOfPaste %}
        <!--поле для налаштування нового пейсту -->
        <div class="settings_area" style="background-color: white; "  >
            <!--шапка поля-->
            <div class="over_grid over_title" style="background-color: #000F2E; ">
                Settings your paste
            </div>
            <!--налаштування-->
            <div >
                 <!--обрання мови-->

                 <div class="labelInputDiv" style="margin-bottom: 60px; ">
                     <label class="baseLabel" for="language">Language</label>
                     {{form.language}}
                </div>

                <!--введення тайтлу-->
                <div class="labelInputDiv">
                    <label class="baseLabel" for="title">Title</label>

                    <input class="baseInput" type="text" id="title" required
                            size="10">

                </div>
                <!--обрання тривалості життя-->
                 <div class="labelInputDiv">
                     <label class="baseLabel" for="expires">Expires</label>
                     {{form.expires}}
                </div>
                <!--обрання категорії-->
                 <div class="labelInputDiv">
                     <label class="baseLabel" for="category">Category</label>
                    {{form.category}}
                </div>
                <!--приватне чи публічне-->
                {% if request.user.is_authenticated %}
                 <div class="labelInputDiv">
                    <label class="baseLabel" for="isPrivate">Is private</label>

                    <input class="baseInput, checkInput" type="checkbox" id="isPrivate" required
                            size="10">
                </div>
                <!--як гість-->
                <div class="labelInputDiv" >
                    <label class="baseLabel" for="asGuest">As guest</label>

                    <input class="baseInput, checkInput" type="checkbox"
                           id="asGuest" required
                            size="10">
                </div>
                {% endif %}
            <!--кнопка створення-->
                {%block button_send%}
            {% if request.user.is_authenticated %}

            <button id="buttonSettings" class="up_pan_buttons sendBtn" style="margin-top: 40px;" onclick="Send('{% url 'create_paste' %}', '{{ csrf_token }}')">Create paste</button>

            {% else %}

            <button class="up_pan_buttons sendBtn" onclick="Send('{% url 'create_paste' %}', '{{ csrf_token }}')">Create paste</button>

            {% endif %}
                {% endblock %}
            </div>

        </div>
        {% endblock %}

        <!--поле для рандомного, що згорає -->
        <div class="sige_paste" style=" border: #000F2E 1px; height: 664px; display: block; font-family: 'JuraBold' "   >
            <!--шапка поля-->
            <div class="over_grid_random over_title_random" style="background-color: #000F2E; ">
                It will burn soon
            </div>
            <!--заголовок для пейсту-->
            <div style=" height: 39px;  border-bottom: 1px solid #788897;">
                <!--назва пейсту-->
                <div style="float: left; font-size: 22px; margin-left: 29px; color: #FFFFFF;" >
                    <a href="{{random_paste_expires.short_url}}" class="header_random_title">{{ random_paste_expires.title }}</a>
                </div>
                <!--автор пейсту та термін-->
                 <div style="float: right; font-size: 16px; margin-right: 29px; color: #81C7EB;">
                     {% if random_paste_expires.author %}
                     {{ random_paste_expires.author }} | {{ random_paste_expires.expires }}
                     {% else %}
                     Guest | {{ random_paste_expires.expires }}
                     {% endif %}
                </div>
            </div>
            <!--текст пейсту-->
            <div id="randomCode2" style="margin-top: 25px;">
            </div>
        </div>
    </div>

{% endblock %}
</body>
<footer>
    <div style="height: 60px;">
    </div>
</footer>
<script>
    var random_paste_language = "{{ random_paste.language }}"
    var burn_paste_language = "{{ random_paste_expires.language }}"
    var random_paste = `{% autoescape off %}{{random_paste.text}}{% endautoescape %}`;
    var burn_paste = `{% autoescape off %}{{random_paste_expires.text}}{% endautoescape %}`;

</script>
{% block for_create_pasteJs %}
<script src="{%static 'js/for_create_paste.js'%}"></script>
{% endblock %}

{% block code_mirrorJs %}
<script src="{%static 'js/code_mirror.js'%}"></script>
{% endblock %}

{% block topBar_randomPasteJs %}
<script src="{%static 'js/topBar_randomPaste.js'%}"></script>
{% endblock %}

{% block endJs %}
{% endblock %}
<script>
    function adjustZoom() {
  var screenWidth = window.screen.width;
  var zoomLevel = screenWidth / 1920; // 1920 - ширина, з якою порівнюємо

  document.body.style.zoom = zoomLevel;
}

// Викликати функцію adjustZoom() при завантаженні сторінки та зміні розміру вікна браузера
window.addEventListener('load', adjustZoom);
window.addEventListener('resize', adjustZoom);
</script>
</html>

syt_app/templates/create_paste.html
{% extends "base.html" %}
{% block code_mirrorJs %}

{% endblock %}

{% block topBar_randomPasteJs %}
{% endblock %}

{% block endJs %}
<script>

  myCodeMirror.setSize(1000, 548);

</script>
{% endblock %}

syt_app/templates/display_paste.html
{% extends "base.html" %}
{% load static %}


<!--<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SYT</title>

&lt;!&ndash; Resources &ndash;&gt;
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.47.0/codemirror.min.css">
    <link rel="stylesheet" href="{%static 'landcss/light.css'%}">
    <link rel="stylesheet" href="{%static 'landcss/dark.css'%}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.47.0/codemirror.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.47.0/mode/javascript/javascript.min.js"></script>
    <script src="{%static 'js/clike.js'%}"></script>
    <script src="{%static 'js/python.js'%}"></script>
    <script src="{%static 'js/go.js'%}"></script>
    <script src="{%static 'js/php.js'%}"></script>
    <script src="{%static 'js/html.js'%}"></script>


    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="{% static 'create_paste.css' %}">

</head>
<body class="main_bg">

    &lt;!&ndash;основна частина &ndash;&gt;
    <div class="main_grid" onLoad="await new Promise(resolve => setTimeout(resolve, 1000))">
        &lt;!&ndash;біле поле для нового пейсту&ndash;&gt;
        <div class="text_area" style="background-color: white;  height: auto; grid-row: 1/3;"   >
            &lt;!&ndash;шапка поля &ndash;&gt;
            <div class="over_grid over_title" style="background-color: #000F2E; width: 700px;">
                {{ paste.title }}
            </div>
            &lt;!&ndash;текст створеного пейсту&ndash;&gt;
            <div style="margin: 0px 50px 0px 50px">
               <textarea id="codeeditor" rows="40" cols="100" class="child_text_area" ></textarea>
            </div>
            <div style="border-top: 1px solid #778796; "  >
                <div class=" baseLabel">
                    <div class="labelInputDiv">
                        <div>Language</div>
                        <div>{{ paste.language }}</div>
                    </div>
                    <div class="labelInputDiv">
                        <div>Category</div>
                        <div>{{ paste.category }}</div>
                    </div>
                    <div class="labelInputDiv">
                        <div>Expires</div>
                        <div>{{ paste.expires }}</div>
                    </div>


                </div>


            </div>
        </div>
        &lt;!&ndash;поле для рандомного пейсту &ndash;&gt;
        <div class="sige_paste"  style=" border: #000F2E 1px; height: 664px; display: block; font-family: 'JuraBold' ">
            &lt;!&ndash;шапка поля &ndash;&gt;
            <div  class="over_grid_random over_title_random "  style="background-color: #000F2E; ">
                Random paste
            </div>
            &lt;!&ndash;заголовок для пейсту&ndash;&gt;
            <div  style=" height: 39px;  border-bottom: 1px solid #788897;">
                &lt;!&ndash;назва пейсту&ndash;&gt;
                <div  style="float: left; font-size: 22px; margin-left: 29px; color: #FFFFFF;" >
                    <a href="{{random_paste.short_url}}" class="header_random_title">{{ random_paste.title }}</a>
                </div>
                &lt;!&ndash;автор пейсту&ndash;&gt;
                 <div style="float: right; font-size: 16px; margin-right: 29px; color: #81C7EB;">
                     {{ random_paste.author }}
                </div>
            &lt;!&ndash;текст пейсту&ndash;&gt;
            </div>
            &lt;!&ndash;текст пейсту &ndash;&gt;
            <div id="randomCode" style="margin-top: 25px;">

            </div>

        </div>

        &lt;!&ndash;поле для рандомного, що згорає &ndash;&gt;
        <div class="sige_paste" style=" border: #000F2E 1px; height: 664px; display: block; font-family: 'JuraBold' "   >
            &lt;!&ndash;шапка поля&ndash;&gt;
            <div class="over_grid_random over_title_random" style="background-color: #000F2E; ">
                It will burn soon
            </div>
            &lt;!&ndash;заголовок для пейсту&ndash;&gt;
            <div style=" height: 39px;  border-bottom: 1px solid #788897;">
                &lt;!&ndash;назва пейсту&ndash;&gt;
                <div style="float: left; font-size: 22px; margin-left: 29px; color: #FFFFFF;" >
                    <a href="{{random_paste_expires.short_url}}" class="header_random_title">{{ random_paste_expires.title }}</a>
                </div>
                &lt;!&ndash;автор пейсту та термін&ndash;&gt;
                 <div style="float: right; font-size: 16px; margin-right: 29px; color: #81C7EB;">
                     {% if random_paste_expires.author %}
                     {{ random_paste_expires.author }} | {{ random_paste_expires.expires }}
                     {% else %}
                     Guest | {{ random_paste_expires.expires }}
                     {% endif %}
                </div>
            </div>
            &lt;!&ndash;текст пейсту&ndash;&gt;
            <div id="randomCode2" style="margin-top: 25px;">
            </div>
        </div>
    </div>
</body>
<footer>
    <div style="height: 60px;">
    </div>
</footer>





</html>-->

{% block styleBlock %}
<style>
    .text_area {
     grid-row: 1/3;
        height: auto;
    }
</style>

{% endblock %}


{% block for_create_pasteJs %}
{% endblock %}

 {% block settingsOfPaste %}
 {% endblock %}

{% block endJs %}
<script>
 document.getElementById("mainTitle").innerHTML = '{{paste.title}}';
   var text_var = `{% autoescape off %}{{paste.text}}{% endautoescape %}`;
    myCodeMirror.setOption("value", text_var);
    myCodeMirror.setOption("mode", '{{paste.language}}');
  myCodeMirror.setSize(1000, 1000);

</script>
{% endblock %}

syt_app/templates/edit_paste.html
{% extends "base.html" %}
{% load static %}

{% block code_mirrorJs %}
{% endblock %}

{% block topBar_randomPasteJs %}
{% endblock %}

{%block button_send%}
            {% if request.user.is_authenticated %}

            <button id="buttonSettings" class="up_pan_buttons sendBtn" style="margin-top: 40px;" onclick="Send('{% url 'edit_user_paste' short_url=short_url %}', '{{ csrf_token }}')">Create paste</button>

            {% else %}

            <button class="up_pan_buttons sendBtn" onclick="Send('{% url 'edit_user_paste' short_url=short_url %}', '{{ csrf_token }}')">Create paste</button>

            {% endif %}
                {% endblock %}

{% block endJs %}
<script>
    document.getElementById("mainTitle").innerHTML = '{{form.title.value}}';
    var text_var = `{% autoescape off %}{{form.text.value}}{% endautoescape %}`;
    document.getElementById("buttonSettings").innerHTML = 'Edit paste';
    //document.getElementById("buttonSettings").onclick = Send(window.location.href, '{{ csrf_token }}');
    //document.getElementById("buttonSettings").addEventListener('click',  Send(window.location.href, '{{ csrf_token }}'), false);

    myCodeMirror.setOption("value", text_var);
    language_select.value= `{{form.language.value}}`;
    document.getElementById("title").value = `{{form.title.value}}`;
    document.getElementById("id_expires").value = `{{form.expires.value}}`;
    document.getElementById("id_category").value = `{{form.category.value}}`;
    document.getElementById("isPrivate").checked = '{{form.is_private.value}}' == 'True'
    document.getElementById("asGuest").checked = `{{form.as_guest.value}}`!= 'None';
    console.log('start')
    console.log(`{{form.as_guest.value}}`)
    console.log(`{{form.is_private.value}}`)


</script>
{% endblock %}