accounts/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('loginpage/', views.loginPage, name="loginpage"),
    path('loginpage1/', views.loginpage1, name="loginpage1"),
    path('registerpage/', views.registerPage, name="registerpage"),
    path('logout/', views.logoutUser, name="logout"),
   # path('', views.home, name='home'),
    path('activate/<slug:uidb64>/<slug:token>',
         views.activate, name='activate'),
    #path('accounts/', views.signup_redirect, name='signup_redirect'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),

]

knu_tech_prac/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import ResetPasswordView
urlpatterns = [
    path("", include("syt_app.urls")),
    path("statistics/", include("stats.urls")),
    path("user/", include("stats.userUrls")),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path("accounts/", include("allauth.urls")),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('accounts/', include('social_django.urls', namespace="social")),

]

stats/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.StatsView.as_view(), name="statistics"),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import User


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

accounts/views.py
from django.dispatch import receiver
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.http import HttpResponse, HttpResponseRedirect
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CreateUserForm as SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .token import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from allauth.account.utils import perform_login
from allauth.exceptions import ImmediateHttpResponse
from allauth.socialaccount.signals import pre_social_login
from django.conf import settings


@receiver(pre_social_login)
def link_to_local_user(sender, request, sociallogin, **kwargs):
    email_address = sociallogin.account.extra_data['email']
    users = User.objects.filter(email=email_address)
    if users:
        user = users[0]
        if user.is_active:
            perform_login(request, user, email_verification=False)
            raise ImmediateHttpResponse(
                redirect(settings.LOGIN_REDIRECT_URL.format(id=request.user.id)))
        else:
            raise ImmediateHttpResponse(redirect('loginpage'))


# Create your views here.


def loginPage(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            form = login(request, user)
            messages.success(request, f' wecome {username} !!')
            return redirect('create_paste')
        else:
            messages.info(request, f'account done not exit plz sign in')
    form = CreateUserForm()
    return render(request, 'accounts/loginpage.html', {'form': form, 'title': 'log in'})

def loginpage1(request):
    return redirect('accounts:loginpage')
def registerPage(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            # save form in the memory not in database
            to_email = form.cleaned_data.get('email')
            users = User.objects.filter(email=to_email)
            if users:
                user = users[0]
                if user.is_active:

                    return render(request, 'accounts/already_exist.html')
                elif user.is_active == 0:

                    return render(request, 'accounts/already_exist.html')
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            # to get the domain of the current site
            current_site = get_current_site(request)
            mail_subject = 'Activation link of your account'
            message = render_to_string('accounts/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })

            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()

            return render(request,'accounts/please_confirm.html')
    else:
        form = SignupForm()
    return render(request, 'accounts/registerpage.html', {'form': form})


@login_required
def logoutUser(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("create_paste")


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, 'accounts/confirmed_user.html')

    else:
        return HttpResponse('Activation link is invalid!')


def signup_redirect(request):
    messages.error(request, "Something wrong here, it may be that you already have account!")
    return redirect("home.html")


def password_reset_complete(request):
    return redirect("password_reset_complete.html")


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'password/password_reset.html'
    email_template_name = 'password/password_reset_email.html'
    subject_template_name = 'password/password_reset_subject.html'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('accounts:loginpage')

accounts/templates/accounts/acc_active_email.html
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

accounts/templates/accounts/already_exist.html
{% load socialaccount %}
{% load static %}
<html>
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <title>Login</title>
    <style>
        body {
            background: radial-gradient(56.06% 56.06% at 50% 50%, rgba(226, 238, 243, 0) 0%, #C1D4DE 100%);
            mix-blend-mode: normal;
            background-attachment: fixed;
        }
    </style>

</head>
<body>
<div style="margin: 0px 50px 0px 50px; justify-content: center; ">
                <div class="card shadow-2-strong" style="border-radius: 1rem;background: linear-gradient(236.18deg, #16304B 16.12%, rgba(22, 48, 75, 0.58) 93.17%); box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.5);border-radius: 5px;margin: 0px 50px 0px 50px; justify-content: center;">
                    <i style="color:white">This email already in use or you need to confirm it</i>
                </div>
 </div>
</body>
{% endblock %}

accounts/templates/accounts/confirmed_user.html
{% load socialaccount %}
{% load static %}
<html>
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Login</title>
    <style>
        body {
            background: radial-gradient(56.06% 56.06% at 50% 50%, rgba(226, 238, 243, 0) 0%, #C1D4DE 100%);
            mix-blend-mode: normal;
            background-attachment: fixed;
            font-family: JuraBold;
        }
    </style>

</head>
<body>
<div style="margin: 0px 50px 0px 50px; justify-content: center; ">
                <div class="card shadow-2-strong" style="border-radius: 1rem;background: linear-gradient(236.18deg, #16304B 16.12%, rgba(22, 48, 75, 0.58) 93.17%); box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.5);border-radius: 5px;margin: 0px 50px 0px 50px; justify-content: center;">
                    <i style="color:white">Thank you for your email confirmation. Now you can login your account.</i>
                </div>
 </div>
</body>
{% endblock %}

accounts/templates/accounts/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'main.css' %}">

</head>
<body style="font-family: JuraBold;">

<div class = "wrapper">
  <nav class="navbar navbar bg-primary navbar-dark">

        <div class="col-sm-6" style="text-align:right;">
          <a class="navbar-brand" href="/"> Home </a>
          {% if user.is_authenticated %}
            <a class="navbar-brand" href="/logout/">LOGOUT</a>
            <a class="navbar-brand" href="/">Welcome-{{user.username}}</a>
          {% else %}
            <a class="navbar-brand" href="/loginpage"> Login </a>
            <a class="navbar-brand" href="/registerpage"> Register </a>
          {% endif %}
        </div>
    </div>
  </nav>
</div>
{% include 'accounts/message.html' %}

<div style="min-height: 90vh">
  {% block content %}




  {% endblock %}
</div>

<footer
        class="text-center text-lg-start text-white"
        style="background-color: #1c2331"
        >
  <section
           class="d-flex justify-content-between p-4"
           style="background-color: #6351ce"
           >


  </section>
  <section class="">
    <div class="container text-md-start mt-5">
      <div class="row mt-3">
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold">DevDuniya</h6>
          <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
              />
          <p style="text-align:left;">
            Login and Register Project in DJango
          </p>
        </div>
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4 text-left">
          <h6 class="text-uppercase fw-bold">Pages</h6>
          <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
              />
              <div style="text-align:left;">
                <a href="/" class="text-white">Home</a><br>
              </div>
        </div>
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4 text-left" >
          <h6 class="text-uppercase fw-bold">Contact</h6>
          <hr
              class="mb-4 mt-0 d-inline-block mx-auto"
              style="width: 60px; background-color: #7c4dff; height: 2px"
              />

        </div>
      </div>
    </div>
  </section>

</footer>
</div>
</body>
</html>

accounts/templates/accounts/loginpage.html
{% load socialaccount %}
{% load static %}
<html>
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Login</title>
    <style>
        body {
            background: radial-gradient(56.06% 56.06% at 50% 50%, rgba(226, 238, 243, 0) 0%, #C1D4DE 100%);
            mix-blend-mode: normal;
            background-attachment: fixed;
            font-family: JuraBold;
        }
    </style>

</head>
<body>
<section class="mainclass">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5" style="">
                <div class="card shadow-2-strong" style="border-radius: 1rem;background: linear-gradient(236.18deg, #16304B 16.12%, rgba(22, 48, 75, 0.58) 93.17%);
box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.5);
border-radius: 5px;">
                    <div class="card-body p-5 text-center">
                         <img src="{% static 'pngfolder/person.png' %}" width="100x" style="position: absolute;top: -60px;left: calc(50% - 50px);">

                        <form method="POST"  enctype="multipart/form-data" class="inputfield">
                            {% csrf_token %}
                            <div class="row" >
                                <input  name="username"  class="form-control"
                                                maxlength="254" required id="id_username"
                                               placeholder="Username" style="width: 80%;margin-left: 10%">
                                <input type="password" name="password"  class="form-control"
                                                maxlength="254" required id="id_password"
                                               placeholder="Password" style="width: 80%;margin-left: 10%;margin-top:5%">
                                </div>

                            <p class="text-center mt-4 mb-0" style="color: white">Don"t have an account? <a
                                    href="{% url 'accounts:registerpage' %}" class="fw-bold text-body"><i
                                    style="color: cornflowerblue">Sign
                                up.</i></a></p>
                            <a href="{% url 'password_reset' %}"><i style="color: cornflowerblue">Forgot
                                Password?</i></a>
                            <div>

                                <button style=" background-color: white; width: 85%;text-align: center;margin-top: 5%;"
                                        class="btn">
                                    <img src="{% static 'pngfolder/google.png' %}" >
                                    <a href="{% provider_login_url 'google' method = 'oauth2' %}" style="color:black;">
                                        Login with Google
                                    </a></button>
                            </div>

                            <div>

                                <button style=" background-color: white; width: 85%; text-align: center;margin-top: 2%"
                                        class="btn">
                                    <img src="{% static 'pngfolder/facebook.png' %}" style="position: relative;">
                                    <a href="{% url 'social:begin' 'facebook' %}"style="color:black;">Login with Facebook</a>
                                </button>
                            </div>
                            <div>

                                <button style=" background-color: white; width: 85%; text-align: center;margin-top: 2%"
                                        class="btn">
                                    <img src="{% static 'pngfolder/github.png' %}" style="position: relative;">
                                    <a href="{% url 'social:begin' 'github' %}" style="color:black">Login with Github</a>
                                </button>
                            </div>

                            <div class="d-flex justify-content-center"
                                 style="position: absolute; background-color: transparent; width: 85%;text-align:center;left:8%;margin-top:7%; background: rgba(0, 15, 46, 0.8);
border-radius: 5px;">
                                <button style=" background-color: transparent;color: white; font-size: 30px" type="submit"
                                        class="btn btn-block btn-lg"
                                        value="Submit">
                                    LOGIN
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>

{% endblock %}

</html>

accounts/templates/accounts/message.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" style="position: absolute;
    z-index: 1;
    right: 0px;
    background-color: skyblue;
    top: 88px;">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}

accounts/templates/accounts/please_confirm.html
{% load socialaccount %}
{% load static %}
<html>
{% block content %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Login</title>
    <style>
        body {
            background: radial-gradient(56.06% 56.06% at 50% 50%, rgba(226, 238, 243, 0) 0%, #C1D4DE 100%);
            mix-blend-mode: normal;
            background-attachment: fixed;
            font-family: JuraBold;
        }
    </style>

</head>
<body>
<div style="margin: 0px 50px 0px 50px; justify-content: center; ">
                <div class="card shadow-2-strong" style="border-radius: 1rem;background: linear-gradient(236.18deg, #16304B 16.12%, rgba(22, 48, 75, 0.58) 93.17%); box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.5);border-radius: 5px;margin: 0px 50px 0px 50px; justify-content: center;">
                    <i style="color:white">Please confirm your email address to complete the registration</i>
                </div>
 </div>
</body>
{% endblock %}

accounts/templates/accounts/registerpage.html
{% load static %}

<html>
 {% block content %}
<head>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'main.css' %}">

	<title>Login</title>
  <style>
    .mainclass {
    background: radial-gradient(56.06% 56.06% at 50% 50%, rgba(226, 238, 243, 0) 0%, #C1D4DE 100%);
    mix-blend-mode: normal;
    background-attachment: fixed;
    font-family: JuraBold;
  }
  </style>

</head>
<body class="mainclass">
<section>
  <div class="mask d-flex align-items-center h-100 " style="padding-top:20px;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="background: linear-gradient(236.18deg, #16304B 16.12%, rgba(22, 48, 75, 0.58) 93.17%);
box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.5);
border-radius: 5px;">
            <div class="card-body p-5 mt-5 mb-0">
               <img src="{% static 'pngfolder/person.png' %}" width="130x" style="position: absolute;top: -65px;left: calc(50% - 65px);">

              <form method="POST" enctype="multipart/form-data" class="inputfield">
                {% csrf_token %}
                <div class="row">

                  <div class="col-sm-6"style="left: 20%">
                    <input  name="username"  class="form-control"
                                                maxlength="254" required id="id_username"
                                               placeholder="Username" style="margin-top: 5%;width: 120%">
                    <input  name="email"  class="form-control"
                                                maxlength="254"
                                               placeholder="Email" style="margin-top: 5%;width: 120%">
                    <input  name="password1"  class="form-control"
                                              type="password"
                                                maxlength="254"
                                               placeholder="Paswword" style="margin-top: 5%;width: 120%">
                    <input  name="password2"  class="form-control"
                                                maxlength="254"
                                              type="password"
                                          placeholder="Password" style="margin-top: 5%;width: 120%">
<!--                    {{form.username}}-->
<!--                    {{form.email}}-->
<!--                    {{form.password1}}-->
<!--                    {{form.password2}}-->
                  </div>
                </div>


                <p class="text-center  mt-5 mb-0"style="color: white">Have already an account? <a href="{% url 'accounts:loginpage' %}" class="fw-bold text-body"><u style="color: cornflowerblue">Log in here</u></a></p>
                <div class="btn" style="position: absolute; width: 85%;text-align:center;left:8%;margin-top:7%; background: rgba(0, 15, 46, 0.8);">
                  <button type="submit" class="btn" value="Submit"
                          style="  color:white;background-color: transparent; font-size: 30px">
                    Register
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</body>
{% endblock %}
</html>

accounts/templates/accounts/signup_closed.html
{% load i18n %}

{% block head_title %}{% trans "Sign Up Closed" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Up Closed" %}</h1>

<p>{% trans "We are sorry, but the sign up is currently closed." %}</p>