knu_tech_prac/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import ResetPasswordView
urlpatterns = [
    path("", include("syt_app.urls")),
    path("statistics/", include("stats.urls")),
    path("user/", include("stats.userUrls")),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path("accounts/", include("allauth.urls")),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('accounts/', include('social_django.urls', namespace="social")),

]

stats/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.StatsView.as_view(), name="statistics"),
]

stats/models.py
from django.db import models

# Create your models here.

stats/forms.py
from django import forms


class ModifyUserForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput())

    class Meta:
        fields = ["email", "password"]


class SortAndSearchPasteForm(forms.Form):
    CHOICES = [("title", "Title"),
               ("text", "Text"),
               ("pub_date", "Publication Date"),
               ("expires", "Expiration Date"),
               ("language", "Language"),
               ("category", "Category")]
    sorting_choice = forms.ChoiceField(choices=CHOICES)
    reverse_sorting = forms.BooleanField(required=False)
    search_string = forms.CharField(required=False)

stats/views.py
from django.shortcuts import render
from django.views.generic import View
from syt_app.models import Paste
from datetime import datetime, timedelta
from stats.forms import ModifyUserForm, SortAndSearchPasteForm
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from stats.filters import PasteFilter
from django.db.models import Q
from syt_app.utils import generate_side_panel_content


class StatsView(View):
    template_name = "stats.html"

    def get(self, request, *args, **kwargs):
        # stats for all
        pastes = Paste.objects.all()

        current_time = datetime.combine(datetime.now(), datetime.now().time(), Paste.objects.filter(expires__isnull=False)[0].expires.tzinfo)
        day_from_now = current_time + timedelta(hours=24)

        all_pastes = pastes.count()
        all_public = pastes.filter(is_private=False).count()
        all_expire_soon = pastes.filter(is_private=False, expires__range=[current_time, day_from_now]).count()
        all_permanent = pastes.filter(is_private=False, expires__isnull=True).count()
        all_available = pastes.filter(is_private=False, expires__gt=current_time).count() + all_permanent

        hour_ago = current_time - timedelta(minutes=60)
        eight_hours_ago = current_time - timedelta(hours=8)
        day_ago = current_time - timedelta(hours=24)
        three_days_ago = current_time - timedelta(days=3)
        week_ago = current_time - timedelta(days=7)
        month_ago = current_time - timedelta(days=30)
        pastes_last_hour = pastes.filter(pub_date__gt=hour_ago).count()
        pastes_last_8_hours = pastes.filter(pub_date__gt=eight_hours_ago).count()
        pastes_last_day = pastes.filter(pub_date__gt=day_ago).count()
        pastes_last_3_days = pastes.filter(pub_date__gt=three_days_ago).count()
        pastes_last_week = pastes.filter(pub_date__gt=week_ago).count()
        pastes_last_month = pastes.filter(pub_date__gt=month_ago).count()
        random_paste, random_paste_expires = generate_side_panel_content(1)

        if not request.user.is_authenticated:
            return render(request, self.template_name, context={'user_authenticated': False,
                                                                'all_pastes': all_pastes,
                                                                'all_public': all_public,
                                                                'all_private': all_pastes - all_public,
                                                                'all_available': all_available,
                                                                'all_expire_soon': all_expire_soon,
                                                                'all_permanent': all_permanent,
                                                                'all_last_day': pastes_last_day,
                                                                'all_last_hour': pastes_last_hour,
                                                                'all_last_8_hours': pastes_last_8_hours,
                                                                'all_last_3_days': pastes_last_3_days,
                                                                'all_last_week': pastes_last_week,
                                                                'all_last_month': pastes_last_month,
                                                                'random_paste': random_paste,
                                                                'random_paste_expires': random_paste_expires
                                                                } )

        # stats for user
        user_name = request.user.username
        user_pastes = Paste.objects.filter(author=request.user.id)
        user_all = user_pastes.count()
        user_public = user_pastes.filter(is_private=False).count()
        user_permanent = user_pastes.filter(is_private=False, expires__isnull=True).count()
        user_available = user_pastes.filter(is_private=False, expires__gt=current_time).count() + user_permanent

        user_expire_soon = user_pastes.filter(expires__gt=current_time,
                                              expires__lt=day_from_now).count()
        user_pastes_last_hour = user_pastes.filter(pub_date__gt=hour_ago).count()
        user_pastes_last_eight_hours = user_pastes.filter(pub_date__gt=eight_hours_ago).count()
        user_pastes_last_day = user_pastes.filter(pub_date__gt=day_ago).count()
        user_pastes_last_3_days = user_pastes.filter(pub_date__gt=three_days_ago).count()
        user_pastes_last_week = user_pastes.filter(pub_date__gt=week_ago).count()
        user_pastes_last_month = user_pastes.filter(pub_date__gt=month_ago).count()

        return render(request, self.template_name, context={'user_authenticated': True,
                                                            'user_name': user_name,
                                                            'all_pastes': all_pastes,
                                                            'all_public': all_public,
                                                            'all_private': all_pastes - all_public,
                                                            'all_available': all_available,
                                                            'all_expire_soon': all_expire_soon,
                                                            'all_permanent': all_permanent,
                                                            'all_last_hour': pastes_last_hour,
                                                            'all_last_8_hours': pastes_last_8_hours,
                                                            'all_last_day': pastes_last_day,
                                                            'all_last_3_days': pastes_last_3_days,
                                                            'all_last_week': pastes_last_week,
                                                            'all_last_month': pastes_last_month,
                                                            'user_all': user_all,
                                                            'user_public': user_public,
                                                            'user_private': user_all-user_public,
                                                            'user_available': user_available,
                                                            'user_expire_soon': user_expire_soon,
                                                            'user_permanent': user_permanent,
                                                            'user_last_hour': user_pastes_last_hour,
                                                            'user_last_8_hours': user_pastes_last_eight_hours,
                                                            'user_last_day': user_pastes_last_day,
                                                            'user_last_3_days': user_pastes_last_3_days,
                                                            'user_last_week': user_pastes_last_week,
                                                            'user_last_month': user_pastes_last_month,
                                                            'random_paste': random_paste,
                                                            'random_paste_expires': random_paste_expires
                                                            })


class UserView(View):
    template_names = ["user.html", "noUser.html"]

    def get(self, request, *args, **kwargs):
        # if not logged in
        if not request.user.is_authenticated:
            return render(request, self.template_names[1], context={})

        user_name = request.user.username

        sorting_choice = request.GET.get('sorting_choice')
        reverse_sorting = request.GET.get('reverse_sorting')
        search_string = request.GET.get('search_string')
        if not sorting_choice:
            sorting_choice = "title"
        sort_form = SortAndSearchPasteForm(initial={'sorting_choice': sorting_choice,
                                                    'reverse_sorting': reverse_sorting,
                                                    'search_string': search_string})

        if reverse_sorting:
            sorting_choice = "-" + sorting_choice

        pastes = Paste.objects.filter(author=request.user.id)
        pastes_filter = PasteFilter(request.GET, queryset=pastes)
        pastes = pastes_filter.qs

        if search_string:
            pastes = pastes.filter(Q(title__contains=f'{search_string}') |
                                   Q(short_url__contains=f'{search_string}') |
                                   Q(text__contains=f'{search_string}'))

        ordered_pastes = pastes.order_by(sorting_choice)
        paginator = Paginator(ordered_pastes, 5)
        paginated_pastes = paginator.get_page(request.GET.get('page'))
        random_paste, random_paste_expires = generate_side_panel_content(1)
        return render(request, self.template_names[0], context={'user_name': user_name,
                                                                'form': pastes_filter.form,
                                                                'sort_form': sort_form,
                                                                'paginated_pastes': paginated_pastes,
                                                                'random_paste': random_paste,
                                                                'random_paste_expires': random_paste_expires
                                                                })


class UserModifyView(View):
    template_names = ["userModify.html", "formAccepted.html"]

    def get(self, request, **kwargs):
        # if not logged in
        if not request.user.is_authenticated:
            return redirect('accounts:loginpage')

stats/templates/formAccepted.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your form is accepted.</title>
</head>
<body>
  <h1>
    Your form is accepted.
  </h1>
  <a class="btn btn-primary" href="/user/modify">Back to the settings</a>
  <a class="btn btn-primary" href="/">Get me back to the main page</a>
</body>
</html>

stats/templates/noUser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>You are not logged in!</title>
</head>
<body>
    <h1>You are not logged in!</h1>
    <a class="btn btn-primary" href="/">Get me back to the main page</a>
</body>
</html>

stats/templates/stats.html
{% extends "base.html" %}
{% load static %}


<style>
#div_piechart {
font-family: 'JuraBold';
  width: 80%;
  height: 400px;
}
#div_barchart {
font-family: 'JuraBold';
  width: 80%;
  height: 400px;
}
</style>
{% block styleBlock %}
<style>
    .text_area {
     grid-row: 1/3;
     height: auto;
    }
    label{
        font-family: 'JuraBold';
        font-style: normal;
        font-weight: 700;
        font-size: 18px;
        width: 100%;
        line-height: 24px;
    }
    h2{
    font-family: 'JuraBold';
        font-style: normal;
        font-weight: 1400;
        font-size: 32px;
        width: 100%;
        line-height: 24px;
        text-decoration: underscore;
    }
</style>
    <script src="https://cdn.amcharts.com/lib/5/index.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/percent.js"></script>
    <script src="{% static 'stats.js' %}"></script>

{% endblock %}




{% block mainPartContent %}

            <div style="margin: 0px 50px 0px 50px">
                <div style="display: grid; grid-template-columns:1fr 1fr 1fr;row-gap: 20px;">
                <label>All present pastes:
                {{ all_pastes }}</label>
                <label>Private pastes:
                {{ all_private }}</label>
                <label>Public pastes:
                {{ all_public }}</label>
                <label>Available pastes:
                {{ all_available }}</label>
                <label>Pastes that expire soon:
                {{ all_expire_soon }}</label>
                <label>Permanent pastes:
                {{ all_permanent }}</label>
                </div>
                <h2>Graphic representation:</h2>
                <div id="div_piechart"></div>
                <br>
                <h2>Pastes created by time period:</h2>
                <br>
                <div id="div_barchart"></div>
                <br>

                {% if user_authenticated %}

                <div style="display: grid; grid-template-columns:1fr 1fr 1fr;row-gap: 20px;">
                <label>Your pastes:
                    {{ user_all }}</label>

                <label>Your private pastes:
                {{ user_private }}</label>

                <label>Your public pastes:
                {{ user_public }}</label>

                <label>Your available pastes:
                {{ user_available }}</label>

                <label>Your pastes that expire soon:
                {{ user_expire_soon }}</label>

                <label>Your permanent pastes:
                {{ user_permanent }}</label>
                </div>
                <h2>Graphic representation:</h2>
                <br>
                <div id="div_userpiechart"></div>
                <br>
                <h2>Your pastes created by time period:</h2>
                <br>
                <div id="div_userbarchart"></div>
                <br>

                {% endif %}



            </div>
{% endblock %}

 {% block settingsOfPaste %}
 {% endblock %}



{% block code_mirrorJs %}
{% endblock %}

{% block for_create_pasteJs %}
{% endblock %}



{% block endJs %}
<script>
    console.log('hhhhhhh')
    render_graphs({{ all_last_hour }}, {{ all_last_8_hours }}, {{ all_last_day }}, {{ all_last_3_days }},
{{ all_last_week }}, {{ all_last_month }}, {{ all_pastes }}, {{ all_public }}, {{ all_available }}, {{ all_expire_soon }},
{{ all_permanent }});
{% if user_authenticated %}
render_user_graphs({{ user_last_hour }}, {{ user_last_8_hours }}, {{ user_last_day }}, {{ user_last_3_days }},
{{ user_last_week }}, {{ user_last_month }}, {{ user_all }}, {{ user_public }}, {{ user_available }}, {{ user_expire_soon }},
{{ user_permanent }})
{% endif %}

    document.body.addEventListener("load", function (){
        console.log('stsrt');


    });
    document.getElementById("div_barchart").style.height = '500px'
    document.getElementById("div_piechart").style.height = '500px'
    document.getElementById("div_userpiechart").style.height = '500px'
    document.getElementById("div_userbarchart").style.height = '500px'
 document.getElementById("mainTitle").innerHTML = 'Statistics';

</script>
{% endblock %}

stats/templates/user.html
{% extends "base.html" %}
{% load templatehelpers %}
{% load static %}

{% block styleBlock %}
<style>
    .text_area {
     grid-row: 1/3;
        height: auto;
    }

    table{

        font-family: 'JuraBold';
        font-style: normal;
        font-weight: 700;
        font-size: 18px;
                width: 100%;
        line-height: 24px;
        /* identical to box height */


        color: #000F2E;
    }
    td{
        height: 50px;
        border-bottom: 1px dashed  rgba(0, 15, 46, 0.35);;
    }
        th{
        height: 50px;
        border-bottom: 1px dashed  rgba(0, 15, 46, 0.35);;
    }

    label{
        font-family: 'JuraBold';
        font-style: normal;
        font-weight: 700;
        font-size: 18px;
        width: 100%;
        line-height: 24px;
    }
    select{
        height: 30px;
           font-size: 18px;
        width: 200px;
    }
     select {

          background-position:
            calc(100% - 10px) calc(1em - 8px),
            calc(100% - 15px) calc(1em + 0px),
            calc(100% - 2.5em) 0.5em;


          background-size:
            10px 10px,
            10px 10px,
            1px 1.5em;

        }

        select:focus {

         background-position:
            calc(100% - 10px) calc(1em - 8px),
            calc(100% - 15px) calc(1em + 0px),
            calc(100% - 2.5em) 0.5em;


          background-size:
            10px 10px,
            10px 10px,
            1px 1.5em;

        }
        .over_grid{
            width: calc(100% - 100px);
        }
    #id_fil_sort_form{
        display: grid;
        grid-template-columns:1fr 1.5fr 1fr 1.5fr ;
        row-gap: 1ch;
        place-items: center;

    }
    #id_reverse_sorting{
        float: right;
    }
    #id_search_string{
        width: 200px;
    }
    input[type=submit]{
            width: 100px;
            height: 40px;
            background: #000F2E;
            border-radius: 10px;
            font-family: 'JuraBold';
            font-size: 25px;
            color: #FFFFFF;
            width: 500px;
            margin-top: 23px;
            justify-content:center;
            position: relative;

              margin: auto;
        margin-top: 20px;
            display: block;


    }

    input[type=text] {
          font-family: 'JuraBold';
        font-style: normal;
        font-weight: 700;
        font-size: 18px;
        width: 100%;
        line-height: 24px;
          border: 1px solid rgba(0, 15, 46, 0.5);
            border-radius: 5px;
    }
      input[type=text]:focus{
          outline: 0;
      }
    input[type=checkbox]{
        height: 20px;
            width: 20px;
            float: left;
            accent-color :#000F2E;
    }
    .pages a{
       margin: 5px;

            font-family: 'JuraBold';
            font-size: 25px;
            color: black;
    }
    button{
            width: 90px;
            height: 30px;
            background: #000F2E;
            border-radius: 10px;
            font-family: 'JuraBold';
            font-size: 16px;
            color: #FFFFFF;

            justify-content:center;
            position: relative;

    }
    .main_button{
        width: 200px;
        height: 50px;
        font-size: 28px;
    }
    .header_label{
        font-size: 30px;
        margin-right: 60px;


    }
    .underline{
        border-bottom: 1px dashed #768696;
        margin-left: -20px;
        margin-top: 50px;
        margin-bottom: 50px;
    }
</style>

<script src="{% static 'js/delete.js' %}">
</script>

{% endblock %}
{% block mainPartContent %}
<div>

</div>
<div class="underline"></div>

 <div style="margin-bottom: 50px; ">
     <label  class="header_label"> Filter: </label>

 </div>
<br>


  <form id="id_fil_sort_form" method="get" >
        {{ form}}
        {{ sort_form }}
      <div style="grid-column:  1/5;
      width: 100%">
            <input type="submit" value="Search">
      </div>

    </form>
<div class="underline"></div>
  <br>
 <div style="margin-bottom: 50px; justify-content: center;">
     <label  class="header_label"> Your pastes: </label>
     <button class="main_button"  style="float: right; margin-right: 20px;">
    <a href="{% url 'user_view' %}" style="color: white; text-decoration: none;">
        Show all
    </a>
</button>
 </div>

  <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
            <td>
                TITLE
            </td>
            <td>
                STATUS
            </td>
            <td>
                LANGUAGE
            </td>
            <td>
                CATEGORY
            </td>

            <th colspan="2">
                ACTIONS
            </th>

        </tr>
      </thead>
	{% for paste in paginated_pastes %}
		<tr>
			<td>
				{{ paste.title }}
            </td>
            <td>
                {% if paste.is_private %}
	            Private
                {% else %}
                Public
                {% endif %}
            </td>
            <td class="language_td">
	            {{ paste.language }}
            </td>
            <td>
	            {{ paste.category }}
			</td>
            <td>
                <button class="actionbutton" onclick="window.location.href='{% url 'edit_user_paste' short_url=paste.short_url %}';">
                    <span class="updatebutton">Edit</span>
                </button>
			</td>
            <td>
                 <button  onclick="delete_note('{% url 'delete_paste' paste.id %}', '{{ csrf_token }}');">
                    <span>Delete</span>
                </button>
			</td>
		</tr>
	{% endfor %}
</table>
<div class="pages" style="display: flex;
    justify-content: center;
    width: auto;">
  {% for i in paginated_pastes.paginator.page_range %}
      <a  href="{% relative_url i 'page' request.GET.urlencode %}" >{{ i }}</a>
  {% endfor %}
</div>
{% endblock %}

<div>
    {{ sort_form }}
</div>
{% block for_create_pasteJs %}
{% endblock %}
{% block code_mirrorJs %}
{% endblock %}



{% block settingsOfPaste %}
{% endblock %}
{% block endJs %}
<script>
 document.getElementById("mainTitle").innerHTML = '{{user_name}}';
 var res =  document.getElementsByClassName("language_td") ;
 console.log(res);
 var language = {
        "text/x-python" : "Python",
        "text/x-csharp": "C#",
        "text/x-c++src": "C++",
        "text/x-go": "Go",
        "text/javascript": "JavaScript",
        "text/x-java": "Java",
        "text/x-php": "PHP",
        "text/x-csrc": "C"
 };

 for (let i = 0; i < res.length; i++) {
  res[i].innerText= language[res[i].innerText]
}


</script>
{% endblock %}

stats/templates/userModify.html
{% extends "base.html" %}
{% load static %}
{% block styleBlock %}
<style>




    label{
        font-family: 'JuraBold';
        font-style: normal;
        font-weight: 700;
        font-size: 30px;
        width: 100%;
        line-height: 24px;
    }

        .over_grid{
            width: calc(100% - 100px);
        }

    input[type=submit]{
            width: 100px;
            height: 60px;
            background: #000F2E;
            border-radius: 10px;
            font-family: 'JuraBold';
            font-size: 30px;
            color: #FFFFFF;
            width: 500px;
            margin-top: 23px;
            justify-content:center;
            position: relative;

            margin: auto;
            margin-top: 20px;
            display: block;


    }

    input[type=text], input[type=email], input[type=password]{
        font-family: 'JuraBold';
        font-style: normal;
        font-weight: 700;
        font-size: 28px;
        width: 100%;
        line-height: 24px;
        border: 1px solid rgba(0, 15, 46, 0.5);
        border-radius: 5px;
    }
    input[type=text]:focus{
          outline: 0;
      }




</style>
{% endblock %}
{% block mainPart %}
<div style="justify-content: center; display: grid;"  >
    <div style="width: 878px; height: 688px; margin-top: 220px; ">

                <div id="main_post" class="text_area"   >

                <!--шапка поля -->
                <div id ="mainTitle" class="over_grid over_title" style="background-color: #000F2E; ">
                    User's Settings
                </div>
                  {% block mainPartContent %}
                <!--текст нового пейсту-->
                <div style="margin: 0px 50px 0px 50px; justify-content: center;">
                   <form action="" method="post" style="display: grid;
                   grid-template-columns: 200px auto; grid-row-gap: 30px; grid-column-gap:50px;  ">
                        {% csrf_token %}
                       {{form}}
                       <div style="grid-column:  1/3;
                        width: 100%; margin-top: 70px;">
                           <input type="submit" value="Submit">
                       </div>

                     </form>
                </div>
                {% endblock %}
            </div>

    </div>
</div>
{% endblock %}


<!--

{% block main_panel %}
    <h1>Hello, {{user_name}}!</h1>
    <h2>Change username or email here, with password verification:</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
        <a href="{% url 'password_reset' %}"><i>Change password</i></a>

    <h2>{{error_text}}</h2>
{% endblock %}
{% block random_paste %}
    <b>Random paste</b>
    <br><a href="{{random_paste.short_url}}">{{ random_paste.title }}</a>
    <br>{{ random_paste.text }}
    <br>{{ random_paste.language }}
    <br>{{ random_paste.category }}
{% endblock %}
{% block random_paste_expired %}
    {% if random_paste_expires %}
        <b><a href="{{random_paste_expired.short_url}}">{{ random_paste_expired.title }}</a></b>
        <br>{{ random_paste_expires.text }}
        <br>{{ random_paste_expires.language }}
        <br>{{ random_paste_expires.category }}
    {% else %}
        <b>It will burn soon</b>
        <br>Nothing
        <br>is going
        <br>to burn
        <br>anytime
        <br>soon
    {% endif %}
{% endblock %}-->